aws:
  sqs:
    endpoint: http://localhost:4566
    queue-name: pedidos.fifo 

resilience4j:
  retry:
    instances:
      pedidoListener:
        maxAttempts: 3
        waitDuration: 1s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        retryExceptions:
          - org.springframework.dao.DataAccessException
          - java.net.SocketTimeoutException
          - java.io.IOException 